version: "3.8"

services:
  novel-database:
    container_name: novel-database
    build:
      dockerfile: Dockerfile
      context: ./database

    image: hwnaginkyu42/novel-database

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: novel
      MYSQL_USER: admin
      MYSQL_PASSWORD: k77889302
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
  novel-redis:                        # 서비스명
    container_name: novel-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: hwnaginkyu42/novel-redis
    ports:
      - "6379:6379"

